### ISSUE TITLE
maxDate to the current date is not working even when using moment

### ISSUE THREAD

**Issue by bingorabbit** [Eonasdan/bootstrap-datetimepicker#1018]
Hello,

When I try to set the maxDate to moment() with the useCurrent set to true, the value of the input box doesn't update, although if I added one 1 second using moment.add(1, 's') or moment.endOf('day') it works just fine as per this jsFiddle: http://jsfiddle.net/9bc9t8t6/1/

Is that a normal behavior?

**Comment by Eonasdan** [comment]
you're basically saying "set the time to NOW and don't let user select a time that IS or IS GREATER then NOW".

So I would say that is the expected behavior, wouldn't you?

**Comment by tsjoberg** [comment]
You sure you don't want ```defaultDate: moment()``` instead?

This issue lies in that ```useCurrent``` populates on "show" which happens after initialization. So what's happening is that your date picker is being initialized (lets say 1:00:00 PM - in which ```maxDate``` is now 1:00:00 PM) then you open picker "show" at 1:00:01 PM it fails the ```maxDate``` check (1:00:01 isAfter 1:00:00) and will not set value
