### ISSUE TITLE
Keys not working on second instance

### ISSUE THREAD

**Issue by ivos** [Eonasdan/bootstrap-datetimepicker#1041]
See the home page itself http://eonasdan.github.io/bootstrap-datetimepicker/ for an example.

The first two demo instances are "Minimum Setup" and "Using Locales".

Click into "Minimum Setup" to set focus there. Then follow this key sequence to move focus to second, back to first and back to second:

TAB, Shift+TAB, TAB

Now you are in the second instance ("Using Locales") and the keys are not working there. E.g. pressing DownArrow does not open the calendar popup, etc.

Tried on Chrome 42, Firefox 31 (on Linux).

EDIT: FYI the functions in keyBinds are not called at all.

**Comment by Eonasdan** [comment]
so this issue is related to the way the `keyBinds` function was written. It's not flushing the modifier keys  like shift and control.

I'm sure there is a better way to write this function. The quick fix is to not bind to the modifier keys.

The reason for the RFC label is because the quick fix is a kind of a breaking change if people use it that way.
