### ISSUE TITLE
Enable limiting to round times

### ISSUE THREAD

**Issue by cool-RR** [Eonasdan/bootstrap-datetimepicker#1070]
I want an option to limit the times the user can choose to half-round hours, e.g. 16:00, 16:30, 17:00, etc.

**Comment by Eonasdan** [comment]
You can already do this with the [`stepping`](http://eonasdan.github.io/bootstrap-datetimepicker/Options/#stepping) function

**Comment by cool-RR** [comment]
I couldn't find it in the docs, how do I do this?

**Comment by Eonasdan** [comment]
`stepping: 15`

**Comment by cool-RR** [comment]
Thanks. Then this issue can be about adding this functionality to the docs.

**Comment by Eonasdan** [comment]
.....it's **already** in the docs... which is what I linked you to

**Comment by cool-RR** [comment]
Sorry, this is my mistake. I missed the navigation bar in the docs.

**Comment by otherprod** [comment]
Yop,

Stepping option is not working as i excepted :), i explain i want to work with half hours  but with a stepping of 60 minutes, so i have a default date wich is something like: 2015-09-09 10:30 and a stepping of 60 minutes, the problem is that it s impossible to start from 10:30 unless i have a stepping of 30min wich i dont want beacause i dont want someone book at 10:00

is there a way to do it cleanly ?
