### ISSUE TITLE
click on the datetimepicker not working with viewmode

### ISSUE THREAD

**Issue by marccollin** [Eonasdan/bootstrap-datetimepicker#1167]
hi

i demo here: http://jsfiddle.net/0Ltv25o8/1468/

if i click on input text Date de naissance,  datetimepick work but the button don't work.

if i clik on Date d'entrée input text nothin happen but that work if i click on the button.

why?

**Comment by Senn0** [comment]
I'm not an expert, but if you want both the text field and the button to work, you have to use something like this:

```html
<div class="input-group date" id="birthdatepicker">
    <input type="text" id="birthdate" name="birthdate" class="form-control">
    <span class="input-group-addon">
           <span class="glyphicon glyphicon-calendar"></span>
    </span>
</div>
```

```javascript
$('#birthdatepicker').datetimepicker({
       viewMode: 'years',
       format: 'DD/MM/YYYY',
       allowInputToggle: true
});
```

Same for the "Date d'entrée, if you want both button and text field to work.
If you only want text field, you should bind it to your text field:
```javascript
$('#locationStartDate').datetimepicker({
       viewMode: 'years',
       format: 'DD/MM/YYYY'
});
```
If you only want the button to work, you should use the javascript above, but instead of binding it to the text field, you bind it to the group.

**Comment by marccollin** [comment]
thank workded fine
