### ISSUE TITLE
DisabledHours and disabledTimeIntervals : should check more than 24 times

### ISSUE THREAD

**Issue by dbertha** [Eonasdan/bootstrap-datetimepicker#1177]
Hello there,
When I disable an entire day with disabledTimeIntervals and some hours with disabledHours, the script check for a valid time by incrementing the hours. But after 24 times it throws an exception. If there wasn't the disabledTimeIntervals, I think this could be ok, but with that option it should do more checks.

**Comment by Jivebunny** [comment]
Agree,
I run into the same problem when it's friday after 17:00, the next available moment with my settings is the monday after at 09:00, which is more like 48+ hours.

daysOfWeekDisabled: [0,6],
disabledHours: [00,01,02,03,04,05,06,07,08,17,18,19,20,21,22,23],

In other words, running with office hours can get you in trouble if some-one wants to schedule an appointment when their current time is being in the weekend, and first available moment is 24+ hours away.

Or is there a way to deal with this?

**Comment by ShakurOo** [comment]
Have you found a solution ? I have a same problem. 
I need to disable hours and disable intervalsTime too...

A way should be push an additional array of moments date witch contains additionals interval time disabled.
For example : 
`disabledHours[0,1,2,3,4,5,6,21,22,23]`
should be translade to 
`disabledTimeIntervals: [[moment().hour(0).minutes(0), moment().hour(6).minutes(0)], [moment().hour(21).minutes(0), moment().hour(23).minutes(0)], [others_intervals_dates]]`

but the problem is : This work just for the currentDay (today) instead working for all days...

**Comment by Jivebunny** [comment]
No, I am sorry. I have not solved the issue. I moved on and started using a different library: Pickadate.js. 

No issues with my complex set of moments that I needed. Just no moment.js to use so a bit more JS date math.

**Comment by elli-pirelli** [comment]
Ages but I think I have a soluton:

            $('#DatumZeit').data("DateTimePicker").date(moment().add(1, 'days')).disabledHours(
               [0,1,2,3,4,5,6,7,8,9,10,23,24]
            )
