### ISSUE TITLE
FR: Datepicker instance to persistently store both a display string and a submit string that can have different formats

### ISSUE THREAD

**Issue by ChrisHacker** [Eonasdan/bootstrap-datetimepicker#1190]
I was looking for this feature and found #1168 closed. Here's the use case for us. We store all dates in ISO format. We want to display in a variety of human readable formats which i'm clear the format option allows us to do. However, the datepicker instance doesn't both persistently store the converted ISO value as the actual input value and make both the display and submit value formats available to the DOM for calculations and printing.

**Comment by Eonasdan** [comment]
as was mentioned, in the closed issue, you can get the date from `.data('').date()`. You can write a hook into the submit event to change the input value or whatever you need to do to get the date in the format you need.

The plugin already provides the functions to get the date in whatever format you need with momentjs. If you need a different format server side, then convert it.

I have no plans to add a hook to the submit event since I couldn't possibly do that in a way that make everyone happy. Nor will I add another function that duplicates `.date()`.
