### ISSUE TITLE
Custom 'useCurrent'?

### ISSUE THREAD

**Issue by Jono20202** [Eonasdan/bootstrap-datetimepicker#1193]
Hi,

I am working on a project where I only want to set a default when the user clicks on the datetime field (other wise it will be left blank to be filled in later).

I was hoping this plugin (used extensively throughout the site) would be able to support this through doing something like allowing a custom 'useCurrent' value. I thought defaultDate would be this, however it seems defaultDate is basically just date().

I have created a jsfiddle for this issue, which I have resolved on the third attempt, however I was wondering if there was a cleaner way to do this within the plugin, without making my own event listener?

http://jsfiddle.net/45gs8r4h/3/

Thanks.

**Comment by benbro** [comment]
I also looking for something similar. In my case useCurrent should be set to '00:00:00' of today instead of now().

**Comment by Eonasdan** [comment]
you could listen for `dp.show` and check to see if that picker has a date already using `.date()` and at that point set the date.

**Comment by Jono20202** [comment]
@Eonasdan That's another good solution. I don't know if you could consider this a feature request for a new version (some sort of integrated option for it), if not then this issue can be closed.

Thanks for your awesome plugin :)

**Comment by Eonasdan** [comment]
@Jono20202 I wouldn't consider change the behavior of `useCurrent` since that would be counter-intuitive to the function name. I'm not sure what a good option for this would be. I could picture turning `defaultDate` or  another function into a "compound" value but I that might make things ugly if you don't want to do something like this.

You can edit this issue to reflex a new option/feature to allow something to trigger on first open.

Thanks, glad you like it :)

**Comment by benbro** [comment]
@Eonasdan in my case the widget let the user pick a date (day) without time and getting a timestamp with hours and seconds (current) is counter-intuitive. I would expect useCurrent to have the same resolution as in the format setting.

**Comment by Eonasdan** [comment]
@benbro doesn't it? I would have expected it to also :P. It should, if it doesn't  please open a new issue and provide a jsfiddle
