### ISSUE TITLE
Disable the time feature

### ISSUE THREAD

**Issue by tomgruszowski** [Eonasdan/bootstrap-datetimepicker#1213]
Is it possible to disable the time feature of this picker? 

This is hands down the best bootstrap date picker and it would be nice to use it as a consistent control where time may not be relevant.

**Comment by Eonasdan** [comment]
the picker uses the `format` option to decide what components to show. Set `format` to `LT` or another valid momentjs format string

**Comment by ldonnet** [comment]
Hi,

i see this issue is closed but when I use your plugin in my code I always see a timepicker :

My coffeescript code to load your js on date : 

 ```javascript
jQuery ->
  if( !(Modernizr.inputtypes.date) )
    $("input:not([disabled]):not([readonly])[type='date']").datetimepicker
      viewMode: 'years'
      format: 'L'
      locale: $('html').attr('lang')
 ```

I try also to use format: "DD/MM/YYYY"

And this is a screen capture of the displayed date picker. The time picker with a clock is always here :  
![capture du 2016-03-02 11-39-50](https://cloud.githubusercontent.com/assets/314537/13458090/cdfb0576-e06b-11e5-8d14-79701568c495.jpeg)

**Comment by Eonasdan** [comment]
create a jsfiddle and open your own issue
