### ISSUE TITLE
defaultDate is ignored when maxDate is set

### ISSUE THREAD

**Issue by btecu** [Eonasdan/bootstrap-datetimepicker#1233]
It seems that if I set `maxDate` and I have a `defaultDate`, `maxDate` takes precedence:

http://jsfiddle.net/6q9onx7p/

**Comment by psirotkin** [comment]
This can be circumvented by explicitly setting `useCurrent: false` ([as noted on SO](http://stackoverflow.com/questions/31747344/defaultdate-and-mindate-with-bootstrap-datetimepicker/31750028?noredirect=1#comment51595886_31750028)). I'm not sure if this behaviour is intentional; if it is, a mention in the docs would be helpful.

**Comment by btecu** [comment]
Even better, I can use `date`, which works, but I didn't see any documentation.

**Comment by nick-hs** [comment]
I am having the same issue, but with minDate.

@psirotkin thank you that worked for me!

**Comment by Eonasdan** [comment]
add a note to the docs
