### ISSUE TITLE
minDate and maxDate always uses timezones. Disregards passed Moment

### ISSUE THREAD

**Issue by phrfpeixoto** [Eonasdan/bootstrap-datetimepicker#1294]
I've been struggling to set a min/max date using a regular unix timestamp, and i noticed that the datetimepicker always disregards the passed Moment in UTC, and subtracts my zone offset.

Fiddle: http://jsfiddle.net/ypt78kt8/

Notice that the min moment should be 2015-07-26T06:05:26+00:00, but the widget allows me to select 2015-07-26T04:05:26 (I'm currently in GTM-3).

it actually sets the minDate to 2015-07-26T03:05:26-03:00, and that's not the passed moment.

**Comment by jeremyVignelles** [comment]
Quite the same problem here, at UTC+2 : 
Local time : 11:10

**Comment by jeremyVignelles** [comment]
OK, I tried some a few things after posting and I have to correct some of my assertions:
- The time set to 0 is due to issue #1311 
- With minDate and useCurrent, I tried `minDate: new Date()`, `minDate: moment()`, `minDate: moment().tz('UTC')`. Only the third option let me choose 10:00 UTC. The first two dates were displayed in the input without any time zone ('z' format) identifier

**Comment by jeremyVignelles** [comment]
Regarding my comment about "each time I open the date picker, the time goes back by 2 hours.". This is an issue with the knockout binding. (explained in #1304)
