### ISSUE TITLE
Problem with Clear-button in knockout-binding

### ISSUE THREAD

**Issue by Alex-Sokolov** [Eonasdan/bootstrap-datetimepicker#1304]
Hi! Thanks for great plugin!

JSFiddle with problem: http://jsfiddle.net/vLyjkcxy/2/

Found small bug when trying to use datetime-picker with knockout.
Use custom-binding from [documentation](http://eonasdan.github.io/bootstrap-datetimepicker/Installing/#knockout)

How to reproduce:
1. Open calendar and set date
2. See that in `ScheduledDate` saved value
3. Open calendar again
4. Tap `Clear` button
5. See that field empty, but `ScheduledDate` stored date
6. In console there is an error `Uncaught TypeError: event.date.toDate is not a function`

**Comment by jeremyVignelles** [comment]
Had an issue with the binding provided in the docs, so i replaced:
```
            if (ko.isObservable(value)) {
                if (event.date != null && !(event.date instanceof Date)) {
                    value(event.date.toDate());
                } else {
                    value(event.date);
                }
            }
```
by
```
            if (ko.isObservable(value)) {
                if(event.date === false) {
                    value(null);
                } else {
                    value(event.date);
                }
            }
```

What changed:
- value is stored as a moment(). Otherwise, the Date is used, with the current time zone, bugging the time picker each time you open it. Maybe there is something wrong with the picker itself, but I personnally don't care about having a moment() in the viewmodel rather than a Date. Everything is a moment() so I don't have to handle Date objects, removed conditions.
- when the value is removed, the handler is getting `false` as `event.date`, rather than `null`. I think `null` should be passed instead, higher in the program, but I handled the case here. This code should fix @Alex-Sokolov issue.

**Comment by Alex-Sokolov** [comment]
@jeremyVignelles thanks. But I change `value(null)` to `value('');`
Think if I haven't date, it will empty string in object. And if after edit need to clear date it must stay as empty string

**Comment by jeremyVignelles** [comment]
@Alex-Sokolov I'm glad it helped :)
I didn't understand why you are passing an empty string rather than a null in your observable. Is it a requirement on your side to use `moment()`/`''` rather than `moment()`/`null` ?

@Eonasdan What do you think about my fix? Is it possible to change it in the docs?

**Comment by Alex-Sokolov** [comment]
@jeremyVignelles 
I use list of objects with few properties. When init with ko startup data, some properties filled, some not. When add new object - properties are empty strings, not null. They exist, but empty now.
How text field can be null, if it on page :) I think that way

**Comment by jeremyVignelles** [comment]
OK, thanks for the explanation. :)
When I'm doing MVVM with knockout, my view model and my view are two different concepts.

- In the ViewModel, only objects are handled, and the default value for an object is `null`
- In the text input View, only strings are handled, which lets the user enter what he wants

In the middle, a conversion takes place between the two worlds.

this plugin is somewhere in the middle, because we get objects with the `.date()` method

Maybe it's just because I'm used to strong-typed languages like C#, but I prefer using `null` for cleared objects, but it's just a matter of taste :)

**Comment by Alex-Sokolov** [comment]
Found another bug in binding

Have an object, with date property. When init it value is `2015-07-23T21:00:00Z`
Click datetimepicker. Date change automatically to `2608-07-20T23:06:50.000Z`
Not cool.

Investigate that happens after `update` function in binding.
If `koDate` object - it is a moment(), another way too complicated replacing/parsing/converting to date:
```js
//in case return from server datetime i am get in this form for example /Date(93989393)/ then fomat this
koDate = (typeof (koDate) !== 'object') ? new Date(parseFloat(koDate.replace(/[^0-9]/g, ''))) : koDate;
```
But moment.js can handle this situation. And after change all work as needed
```js
koDate = (typeof (koDate) !== 'object') ? moment(koDate) : koDate;
```

**Comment by jeremyVignelles** [comment]
I had this issue too, but I can't find the documentation topic we are talking about. Maybe it was removed.

Here is my binding:

``` JS
    ko.bindingHandlers.dateTimePicker = {
        init: function (element, valueAccessor, allBindingsAccessor) {
            //initialize datepicker with some optional options
            var options = $.extend(
                {
                    // Insert default values here
                    /*sideBySide: true,timeZone: 'UTC'*/
                },
                allBindingsAccessor().dateTimePickerOptions || {});

            $(element).datetimepicker(options);

            //when a user changes the date, update the view model
            ko.utils.registerEventHandler(element, "dp.change", function (event) {
                var value = valueAccessor();
                if (ko.isObservable(value)) {
                    if (event.date === false) {
                        value(null);
                    } else {
                        value(event.date);
                    }
                }
            });

            ko.utils.domNodeDisposal.addDisposeCallback(element, function () {
                var picker = $(element).data("DateTimePicker");
                if (picker) {
                    picker.destroy();
                }
            });
        },
        update: function (element, valueAccessor) {
            var picker = $(element).data("DateTimePicker");
            //when the view model is updated, update the widget
            if (picker) {
                var koDate = ko.utils.unwrapObservable(valueAccessor());
                picker.date(koDate);
            }
        }
    };
```

**Comment by Alex-Sokolov** [comment]
In moment.js docs - http://momentjs.com/docs/#/parsing/asp-net-json-date/

**Comment by jeremyVignelles** [comment]
Yeah, but the knockout binding has probably been removed from the bootstrap-datetimepicker official docs.

**Comment by jluistorres** [comment]
Add .toDate()

```
if (ko.isObservable(value)) {
                    if (event.date === false) {
                        value(null);
                    } else {
                        value(event.date.toDate());
                    }
                }
```
