### ISSUE TITLE
Setting a format makes datetimepicker return wrong date

### ISSUE THREAD

**Issue by rootuser** [Eonasdan/bootstrap-datetimepicker#1339]
Hello,

I use the following code:

```
       var now = new Date();
       dtp = $('#validouter').datetimepicker({
            locale: 'de',
           // format: 'L',
            //format: 'DD.MM.YYYY',
            calendarWeeks: true,
            showTodayButton: true,
            defaultDate: now
        });

        dtp.on('dp.change', function(e) {
            var tmpdate = e.date._d.toISOString();
            console.log(tmpdate);
        });
```

When I leave it that way, everything will work just fine; locale is loaded and displayed correctly. The event function will put an output like '2015-09-07T11:06:00.000Z' into the browser's console.
But because I don't want the time in the datetimeselector, I use the format like shown above; 'L' or 'DD.MM.YYYY'. When I uncomment one of these, everything will still _seem_ fine, but the output of my event function will always be _one day off_ ! E.G. when I select September 22nd, 2015, I get '2015-09-21T22:00:00.000Z'.

What is happening here? Any ideas?
(I am using version 4.14.30 of the datetimepicker.)

Thank you!
Regards, Tom

_EDIT_
I think I see now whats happening; my local time is GMT+0200, and when I select September 22nd, 2015 (without choosing a time), the two-hour offset is **substracted** from the selected date. 
But that is a bug, not a feature, is it?

**Comment by osadchiynikita** [comment]
Hi, i had the same issue with datetimepicker in my project.

Try to use {format: 'L'} instead of 'DD.MM.YYYY'. It helped me

http://momentjs.com/docs/#/displaying/format/

**Comment by alebacca89** [comment]
Hi,
I had the same problem and I resolved in this way:
I've implemented a function to parse data using this api:

  var parseInputDate = function(inputDate){
      return moment(inputDate, FORMAT_OF_DATE);
};
$("#idofyourelement).data("DateTimePicker").parseInputDate(parseInputDate);

Bye

**Comment by tomassna** [comment]
+1
To me it seems that setting a renderformat makes it crash as it is unable to parse the date. 

I have a requirement to display according to UK standard (dd/MM/yyyy HH:mm according to en_GB locale). It crashes on inizialisation when it is unabe to parse minDate.

The getMoment function defined at line 140 has a bunch of TODO:s that indicates that format and locales are not really supported yet, but still, it is something that I would really need for the brittish users.

Thanks for an otherwise well functioning picker.
