### ISSUE TITLE
Datetimepicker not working inside table-responsive

### ISSUE THREAD

**Issue by danijelGombac** [Eonasdan/bootstrap-datetimepicker#1346]
Datetimepicker not working inside table-responsive.

Look: https://jsfiddle.net/0Ltv25o8/1886/

Remove class table-responsive from div and working how it must. The version 3.1.3 in Opencart 2.1 is working OK with table-responsive.

**Comment by EmersonMellado** [comment]
Hey. I am not having the same issue. It continues to bother you?

**Comment by lenichols** [comment]
Having the same issue.

**Comment by nikunj24u** [comment]
yes, I am also having same issue with table-responsive.

**Comment by emersonmellado** [comment]
@nikunj24u Could you, please, upload an image of what is happening? And a part of your code, if possible.

Thanks.

**Comment by nikunj24u** [comment]
@emersonmellado, Please find screenshots as attachments.
In table-responsive class, I have changed override the overflow:auto to overflow:visible, which solve the issue and DateTimePicker dialog gets visible properly in large screens i.e. for laptop and desktop (Screenshot 1). But because of overflow:visible table-responsive looses the scrollbar in small and medium screens(screenshot 2). Now in firebug if I disable overflow:visible, table-responsive gets the scrollbar in small screen(screenshot 3).
![1](https://cloud.githubusercontent.com/assets/4158666/14525941/b45df8da-025d-11e6-81af-ac7248f73138.png)
![2](https://cloud.githubusercontent.com/assets/4158666/14525945/b84f49e4-025d-11e6-90dc-2a9d70fdbb57.png)
![3](https://cloud.githubusercontent.com/assets/4158666/14525946/ba3bde7a-025d-11e6-8b17-0279b3cbf30f.png)

Thank you.

**Comment by nikunj24u** [comment]
@emersonmellado, I believe, the issue is DateTimePicker dialog is created just under its creator textbox. So both, textbox and created DateTimePicker are inside table-responsive class. If DateTimePicker can be created just before body tags ends and set its top-left according to its creator textbox top-left, this type issue can be solved. As I do not know how the jquery is written, I can not say much about the soluiton, just take it as a suggestion only. 
![4](https://cloud.githubusercontent.com/assets/4158666/14526420/c584564c-0260-11e6-8e1a-c3bea0cec574.png)

As I am running little tight on time, I will appreciate if you provide any solution or workaround. 

Thank you,
Nikunj Patel

**Comment by emersonmellado** [comment]
Appears to me that the issue is not exactly the "table-responsive" class behavior. On the second image you've sent there is a horizontal scroll bar, right?

I'd try, as a workaround, to hide columns on this table by media query. for example:

`@media only screen and (max-device-width: 480px){
    //for header     and    for td to hide 
    tr th:nth-child(2), tr td:nth-child(2),
    tr th:nth-child(3), tr td:nth-child(3),
    tr th:nth-child(4), tr td:nth-child(4),
    {
        display: none;
    }`

It's not the solution, but I believe that if you scroll the table right you'll be able to see the data selection field. That make sense to you?

**Comment by nikunj24u** [comment]
On third image horizontal scrollbar gets visible if I disable overflow:visible in table-responsive class.
See, there two things,
First, to solve DateTimePicker issue with table-responsive class, need to have overflow:visible.
Second, to have a scrollbar on talbe-responsive class in the small/medium grid, need to have overflow:auto/scroll. In that case, DateTimePicker dialog will not appear properly.
So, DateTimePicker dialog appear logic should be changed.
Thank you for the workaround but that will not work in my case as I must show all the columns.
Please do the needful.

**Comment by aman-subscriptions** [comment]
I'm having the same issue.  The table inside div with classes "row table-responsive". On showing date picker it creates scrollbars around the table.

![image](https://cloud.githubusercontent.com/assets/15607412/22190531/dd6bb1dc-e177-11e6-9930-e19af06ad399.png)

**Comment by maikealame** [comment]
Any solution ? the `widgetParent` does not seem to be working great.

**Comment by fnaquira** [comment]
Any solution? I also have this problem

**Comment by William-H-M** [comment]
Currently this doesn't have an easy fix but for now:

this is the dirty-workaround:

```
let $picker = $('.date');
$picker.datetimepicker({});

$picker.datetimepicker().on('dp.show', function() {
  $(this).closest('.table-responsive').removeClass('table-responsive').addClass('temp');
}).on('dp.hide', function() {
  $(this).closest('.temp').addClass('table-responsive').removeClass('temp')
});
```

**Comment by Saqib638** [comment]
I have solved the issue by adding position:relative; rule to .bootstrap-datetimepicker-widget class in bootstrap-datetimepicker.min.js.

**Comment by RicardoBer** [comment]
To any one that has @aman-subscriptions problem (capture 2), you must add this class to your th, td containers.

```
.backgrid th,
.backgrid td {
  display: table-cell;
  position: relative; 
  overflow: visible;
} 
```
I use it within an backbone/backgrid project and it works perfect.

**Comment by Gyyone** [comment]
This Script work for me with bootstrap 4
![image](https://user-images.githubusercontent.com/13106897/68995922-1c577400-08ce-11ea-9351-70fac8b8489e.png)

[tempusdominus-bootstrap-4.txt](https://github.com/Eonasdan/bootstrap-datetimepicker/files/3854400/tempusdominus-bootstrap-4.txt)
