### ISSUE TITLE
ViewMode: 'years'

### ISSUE THREAD

**Issue by Laurent001** [Eonasdan/bootstrap-datetimepicker#1429]
After you select a date in viewMode@years, if you want to modify it, you don't get anymore the viewMode@years.

**Comment by dnessonov** [comment]
Got the same problem. Any suggestions ?

**Comment by junkystu** [comment]
I only get the view mode in years the first time the picker opens. After that, it's the default days view.

**Comment by RoAndrei** [comment]
same problem here. Anyone managed to solved this?

**Comment by ClintYarborough** [comment]
FYI, version 4.15.35 does not have this issue.

**Comment by ggobi74** [comment]
Same problem. The problem is:
- load page: picked is ok, displays year
- click to open: picker displays years to pick from
- close picker (select / don't select, close etc. - doesn't matter)
- open picker again: the picker shows days view, the default
(broken object reference somewhere?)

Downgraded to 4.15.35 and works. Thank you @ClintYarborough

**Comment by RoAndrei** [comment]
Found another solution- using the show event, set the viewMode to the desired state, like this:
`$(this).data("DateTimePicker").viewMode("years");`

**Comment by kaiyulee** [comment]
@junkystu why it works on demo?

**Comment by junkystu** [comment]
@kaiyulee it doesn't. I've just had a quick look. Browse to the `viewMode: 'years'` example, choose a date, and then click away to hide the datepicker. Open it again and you'll see it's in day view rather than years.

**Comment by William-H-M** [comment]
Solved on latest version
