### ISSUE TITLE
useCurrent does not appear to work

### ISSUE THREAD

**Issue by eric79** [Eonasdan/bootstrap-datetimepicker#1544]
The documentation says that an option value of `useCurrent` set to `true` should populate the datetimepicker with the current date and time.  However, it appears to leave the `input` blank.

Fiddle: http://jsfiddle.net/mq6ryp2w/

The workaround is to set:

```
$datetimepickers.datetimepicker( {
    defaultDate: moment()
} );
```

**Comment by Zero3** [comment]
I have the same issue as you, as I expected `useCurrent` to do the same as you expect.

However, the docs actually say: `**On show**, will set the picker to the current date/time`. When I click my datepicker, it does indeed set the date to the current date. So the date part works as documented, it appears.

I also have a timepicker (`format: 'HH. mm'`), but this one is erroneously set to 00:00 instead of the current time. So this feature could definitely use a review.

**Comment by Zero3** [comment]
@William-H-M were these issues fixed?

**Comment by William-H-M** [comment]
Hi, @Zero3 yes this has been solved on latest version using either only date, only hour or both
