### ISSUE TITLE
Keybinding loses control after pressing Enter key on a date

### ISSUE THREAD

**Issue by Spydr331** [Eonasdan/bootstrap-datetimepicker#1690]
So this is my process, the issues I am having I have capitalized
1. I navigate to the input that the date picker is attached to
2. Pressing the down key on the input, I open the date picker
3. I select a date by using the arrow keys to navigate, then pressing the Enter key
4. I navigate back into the input box
5. DOWN KEY NO LONGER WORKS so I click the calendar icon
6. The calendar opens but THE ARROW KEYS NO LONGER NAVIGATE instead they move about the input box content

Has anyone else experienced this issue or knows a fix? It happens in the demo too.

**Comment by Spydr331** [comment]
I figured out the issue.  It was being caused by the tab key not being handled.  I was able to fix it in a jsfiddle, please review to see if it can be put into the base code (I added in some comments with `//FIX` in two locations for easy viewing) https://jsfiddle.net/mfeola/a0zkz5zx/

**Comment by rachirib** [comment]
Hi  @Spydr331,

We got a similar issue here in the project, once we select the date and came back with the tabkeys the arrow keys for left and right no longer navigate not even to move around the field.

The problem was that in the default logic of the plugin if there is no widget open it doesn't do anything, it just return. What I did to fixed was rebind the keys with this, showing the widget if the arrows are pressed.

`$datepicker.datetimepicker({
      format: 'DD-MMM-YYYY',
      useStrict: true,
      minDate: moment('01-Jan-1890', 'DD-MMM-YYYY'),
      maxDate: moment(), 
      keepInvalid: true, 
      useCurrent: false, 
      widgetPositioning: {
        horizontal: 'left',
        vertical: 'bottom'
      },
      ignoreReadonly: true,
      keyBinds: {
        't': null, //we need 't' for dates such as Oct, disable the 't' = today's date feature
        left: function (widget) {
              if (!widget) {
                  this.show();
                  return;
              }
              var d = this.date() || this.getMoment();
              if (widget.find('.datepicker').is(':visible')) {
                  this.date(d.clone().subtract(1, 'd'));
              }
            },
        right: function (widget) {
            if (!widget) {
                this.show();
                return;
            }
            var d = this.date() || this.getMoment();
            if (widget.find('.datepicker').is(':visible')) {
                this.date(d.clone().add(1, 'd'));
            }
        }
      }
    });`

But we still face a problem that if they press enter the field loose focus, can you please repost your fiddle so I can have a look ? (it seems not working)

Thanks!

**Comment by aldzii** [comment]
Hi @rachirib,

I just want to ask where I'm gonna put that code of yours? Sorry I'm just a newbie.

**Comment by hennson** [comment]
Sorry, but the Issue still exists...

**Comment by hennson** [comment]
The error is that keyState gets never reset after selecting a date with Enter or canceling with Escape. To add **keyState = {};** in the hide method fixes this bug.
