### ISSUE TITLE
how to integrate with AngularJS?

### ISSUE THREAD

**Issue by haoramirez** [Eonasdan/bootstrap-datetimepicker#1790]
Is there an easy way to integrate this with the ng-model of AngularJS 1.5?

**Comment by manish-wedig** [comment]
I am also looking for this. if you got the answer from outside. please let me know.

**Comment by alex75it** [comment]
This appear to be a bug to me.
I mean when you use the datepicker it breaks a previous working AngularJS binding.

BEFORE. 
<input type="text" ng-model="date" /> 
This works because when the input value change the $scope.date change.

AFTER.
<input type="text" class="datepicker datetimepicker-date" ng-model="date" /> 
simplified JS > $('.datetimepicker-date')).datetimepicker(...)
This does not work because when the input value change (using the calendar) the $scope.date does not change.

I don't expect to break the "ng-model" binding adding the calendar !
I mean the input value is changed also using the calendar, why this event is no more "seen" by Angular ?

**Comment by shainegordon** [comment]
https://github.com/atais/angular-eonasdan-datetimepicker
