### ISSUE TITLE
Can't select minimum date if time is below minDate

### ISSUE THREAD

**Issue by MitchTalmadge** [Eonasdan/bootstrap-datetimepicker#1793]
https://jsfiddle.net/1rd1p3f9/

Visit the link above and set the time to anything below 11:00 AM, and then attempt to set the date to the 16th of September, 2016. (The minimum date). You will notice that you cannot select the date at all. 

The expected behavior would be that because it is highlighted, I can select it, and the time would automatically revert to the minimum of 11:00 AM. Instead, I cannot select it at all, and, as the end user, I might have no idea why. This could be very frustrating.

My suggestion is to make it so that if your selected time is before the time of minDate and you attempt to click on the minimum actual day, the time will reset to _at least_ the minDate's time.

**Comment by emmgfx** [comment]
Same error here : / any solution?

**Comment by Webkungen** [comment]
Almost same problem here. Date range is May 10-12, 2018:
`$('input[name^="phase_date_"]').datetimepicker({
	format: 'L', useCurrent: false, locale: 'sv'minDate: moment("2018-05-10 00:00:00"), maxDate: moment("2018-05-12 23:59:59")
});`

Problem is on initalize the current view is March and the arrows for changing months are disabled, i.e. cannot "browse" to May in order to select any of the dates. If setting defaultDate to the same as minDate the calendar is initialized correct (showing May) but when setting the option my input is prefilled with that date, which I don't want. The input should be empty until a date is selected.

**Comment by LibrErli** [comment]
same problem here.
user have to select an appropriate time before they can select the date. but that is absolutely not intuitive.
