### ISSUE TITLE
Change time and then date without hiding - only date changes

### ISSUE THREAD

**Issue by SheldonNeilson** [Eonasdan/bootstrap-datetimepicker#1855]
1. Open DateTimePicker
2. Change time
3. Change date

**Time resets to the initial time, while the new date is selected.**

**To force it to work I have to close the DateTimePicker after selecting the time or change the time after the date:**
1. Open DateTimePicker
2. Change time
3. Close DateTimePicker

**Time change is reflected**
1. Open DateTimePicker
2. Change date
3. Close DateTimePicker

**Date and time change is reflected**

Bootstrap v3.3.7
jQuery v3.1.1
moment 2.15.1
bootstrap-datetimepicker v4.17.43

```
            <div class="form-group">
                <label for="filter-from-date">From</label>
                <div id="filter-from-date" class="input-group date">
                    <input type="text"
                           class="form-control"/>
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>
```

```
$(#filter-from-date', this.filterPanel).datetimepicker();
```

**Comment by Edralo** [comment]
I was about to create a new issue about this.

It also does that when you use a date with a different value than "now", for exemple `moment().add(1, 'h')` for a date one hour in the future. In that case, changing directly the date sets the time to "now".

Don't know if that's clear enough, anyway I reverted to version 4.15.35 for now since the issue didn't exist back then.

I also tried to dig inside the module to find what's the cause of the it, but unfortunately I didn't found it precisely. I just found it weird that in the function `selectDay`, we're using a clone of `viewDate` as a basis for the day modification but that variable has the wrong time in it.

                selectDay: function (e) {
                    var day = viewDate.clone();
                    if ($(e.target).is('.old')) {
                        day.subtract(1, 'M');
                    }
                    if ($(e.target).is('.new')) {
                        day.add(1, 'M');
                    }
                    setValue(day.date(parseInt($(e.target).text(), 10)));
                    if (!hasTime() && !options.keepOpen && !options.inline) {
                        hide();
                    }
                },

Exemple :

- If we are now `March 3rd 2016 10:00:00 AM`.
- For my datetimepicker i'll use a variable set by default at now + 1 hour or `March 3rd 2016 11:00:00 AM`.
- I open the picker and click at the date March 5th 2016.
- Then in the `selectDay` function, the clone of `viewDate`will be `March 5th 2016 10:00:00 AM` instead of `March 5th 2016 11:00:00 AM`.

--

Before posting this comment I changed the `selectDay` function to try to fix the issue.

Everything seems to work but I changed the code inside my work project directly as I don't have time right now to fork this repo to launch the tests / modify the tests if necessary and make a PR.

If someone else can do this for me (if those changes are ok) i'll be glad, otherwise I'll do it later when I have the time to figure out everything.

I also didn't touch the two `if`about `$(e.target).is('.old')` and `$(e.target).is('.new')` since I don't know what they're checking right now.

                selectDay: function (e) {
                    viewDate.date(parseInt($(e.target).text(), 10));
                    if ($(e.target).is('.old')) {
                        viewDate.subtract(1, 'M');
                    }
                    if ($(e.target).is('.new')) {
                        viewDate.add(1, 'M');
                    }
                    setValue(date.clone().year(viewDate.year()).month(viewDate.month()).date(viewDate.date()));
                    if (!hasTime() && !options.keepOpen && !options.inline) {
                        hide();
                    }
                    viewUpdate('D');
                },

**Comment by stabbystabstab** [comment]
I've got the same problem. I couldn't find a work around and ended up having to set `sideBySide: true`

**Comment by William-H-M** [comment]
Hi, the latest version, 4.17.47, doesn't have this error.
