### ISSUE TITLE
How do I distinguish `dp.change` event from the UI itself vs calling `.date([newDate])`?

### ISSUE THREAD

**Issue by chanpory** [Eonasdan/bootstrap-datetimepicker#1870]
The `dp.change` event fires when clicking on the picker itself as well as when calling `.date([newDate])` programmatically. Is there a way to distinguish between the two?

**Comment by SaurabhHarwande** [comment]
Please look into this issue.
Even I have a situation where I want to update two date pickers on change of an dropdown. But don't want the change event to fire when I am doing it from javascript.
Can we have this control in line with the standard where the event is not fired when anything is updated from backend. Rather it is more sane to trigger manually at backend using $.trigger rather than forcing it on the user. It seems wrong when the developer is burdened with an event like this.
For now I have worked around by using dp.update event. But it is way too hacky at the moment, will be trying to change js file myself to get this working.
