### ISSUE TITLE
If a user types in date and then moves on to calendar , it shows as 0000 in year

### ISSUE THREAD

**Issue by adilogs** [Eonasdan/bootstrap-datetimepicker#1991]
![pasted image at 2017_01_20_05_14 pm](https://cloud.githubusercontent.com/assets/16147319/22204546/8aabce66-e198-11e6-8e2c-46cd6b47c159.png)

**Comment by William-H-M** [comment]
I've tried multiple times and the only way to get your result was inserthing dates like '12/12/17' this will make the calendar think you're actually inserting year '0017' and not 2017.

Usually thinks like dates shouldn't been allowed for that the user set his own date, format, because it'll be just a big problem as itself, so just put a readonly property an use this
https://github.com/Eonasdan/bootstrap-datetimepicker/issues/1991?_pjax=%23js-repo-pjax-container

**Comment by adilogs** [comment]
@William-H-M:  The issue arises when you put any two-word input from the textbox and then switch over to the calendar. For example in my case, as given in screenshot it I entered 12 from keyboard and then switched over to calendar to get a date like above in screenshot.

Moreover, I searched a lot yesterday and found out a way of handling it by disabling the input from the keyboard. I used

`onkeydown="return false"`

on my input tag and it disables the keyboard input thus leaving the only option of selecting the date from the calendar. I know this is not exactly what I wanted but this removes this issue all out from the datetimepicker.

**Comment by adilogs** [comment]
@William-H-M: Sorry not on input, but on parent div of input you can put 

`onkeydown="return false"`

**Comment by William-H-M** [comment]
Well that's actually another good way to do it if do not want to set up the readonly property another think you should do is set the option the [allowInputToggle](http://eonasdan.github.io/bootstrap-datetimepicker/Options/#allowinputtoggle) that way as soon the input get focus the client won't do anything weird like typing it'll get it that is need it to choose a date.

Now as this is solved please close the issue.
Have a nice day :)
