### ISSUE TITLE
Date changes to local time even with timezone set

### ISSUE THREAD

**Issue by robjbrain** [Eonasdan/bootstrap-datetimepicker#1992]
I am setting my timezone to London time in the datepicker options, however whenever the datepicker is displayed it is showing in my local time (I am currently in Australia).

This causes a problem because I give the datepicker the timestamp "1478334600" which is "2016-11-05 08:30:00" but it appears as "2016-11-05 19:30:00" in the browser.

This is problematic as when the form is submitted, 7.30pm is passed through to PHP even though the user hasn't changed anything. I have no way of knowing what timezone was used by the timepicker so risk updating my database with incorrect information.

I assumed if I give the datetimepicker a timestamp and set a timezone there shouldn't be any confusion about what date is shown, yet there still is.

I can't tell if this is a bug or if i'm missing a feature somewhere which would allow forcing of the timezone.

Here is a JS Fiddle: http://jsfiddle.net/xtvq3x39/4/

How can I give the datetimepicker a timestamp and have the date always shown in the Europe/London timezone?

**Comment by robjbrain** [comment]
I have also attempted to use the momentjs timezone function in their [documentation](http://momentjs.com/timezone/docs/) but always get back an error. This may be part of the solution but i'm unsure.

```js
moment.tz(1478334600, "Europe/London")
```

> Uncaught TypeError: moment.tz is not a function

**Comment by William-H-M** [comment]
Ok I think I got it. See this [Fiddle](http://jsfiddle.net/tyw9dnhb/1/) is that the way you need it?
the only really problems that I saw were:
1) you were not including moment-timezone library and that's way the 
> Uncaught TypeError: moment.tz is not a function
2) Not totally sure the timestap you gave always gave me a date on 1970 maybe is because I didn't formated it with unix time
After that everything worked, as It does show the time on london and tested from my timezone (I'm currently at Colombia)

Hope it helps if anything else need it just say
Good Luck!

**Comment by William-H-M** [comment]
Hi, I'll be closing this as there's no feedback from original poster, feel free to re open it if need it.
