### ISSUE TITLE
onchange event is not working on input field

### ISSUE THREAD

**Issue by gouthamgit** [Eonasdan/bootstrap-datetimepicker#2029]
`<input type='text' onchange='javascript:alert()' name="mypicker"/>`
onchange event is not triggering. I mean, when I change I need to call a function from html tag.

**Comment by FaTaToo** [comment]
Do you solve the problem yet? I also hit this problem.

**Comment by Al10s** [comment]
Same for me, I wanted to use the options "keepInvalid" and "useStrict" to warn the user instead of overwriting its input, but I failed when trying
```js
$('input[name=mypicker]').on('change', onDateChanged);
```

BUT there is another event triggered by the datetimepicker : `dp.change`
So you can do
```js
$('input[name=mypicker]').on('dp.change', onDateChanged);
```

It doesn't trigger a "real" event though, it's a custom one, but you still can catch it to know the input changed

**Comment by William-H-M** [comment]
Hi, I’ll be closing issues that have been answered by the community.

**Comment by mflorea** [comment]
The issue with ``dp.change`` versus ``change`` is that the former is forcing your code (e.g. validation) to be aware of the date picker used. It's not clear from https://getdatepicker.com/4/Events/#dpchange why the custom event was needed or what are its benefits over the standard ``change`` event.
