### ISSUE TITLE
Default date time not working

### ISSUE THREAD

**Issue by codeigniterd** [Eonasdan/bootstrap-datetimepicker#2106]
Hi 

$('#timeanddate').datetimepicker({
                    format: 'DD/MM/YYYY hh:mm a',
					defaultDate: '23/05/2017 09:19 pm',
                    maxDate: moment().add(0, 'days'),
                    clear: null
                });

this code does not showing any value in datetimepicker textbox ?

Can anyone help ! Appreciate

**Comment by William-H-M** [comment]
Hi, the reason this is not working is because moment has depracated that way to put the formats.
Why? [here the reason](http://momentjs.com/docs/#/parsing/string/)

> Warning: Browser support for parsing strings is inconsistent. Because there is no specification on which formats should be supported, what works in some browsers will not work in other browsers.

So you should follow the  [string + format](http://momentjs.com/docs/#/parsing/string-format/)

I did a [fiddle ](https://jsfiddle.net/William_/sbt882mo/1/)to show your case and how it's working

NOTE: I do use useCurrent instead clear, to avoid takin the current date

**Comment by codeigniterd** [comment]
Thank You Very Much @William-H-M . You Saved Me a Lot :)
