### ISSUE TITLE
 can't get right month & day

### ISSUE THREAD

**Issue by c4327611** [Eonasdan/bootstrap-datetimepicker#2108]
http://ppt.cc/fStIm

```
<div class="container">
    <div class="row">
        <div class='col-sm-6'>
            <div class="form-group">
                <div class='input-group date' id='datetimepicker_S'>
                    <input type='text' class="form-control" id="datetime" />
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>
        </div>
    </div>
</div>

<a href="javascript:getDay()">Get</a>
```

```
<script>
function getDay(){
   var myDate = $('#datetimepicker_S').data('DateTimePicker').date();
   var year = myDate.get('year');
   var month = myDate.get('month');
   var day = myDate.get('day');
   var hour = myDate.get('hour');
   var minute = myDate.get('minute');
   var Second = myDate.get('seconds');
   alert(year + "-" + month + "-" + day + " " + hour + ":" + minute + ":" + Second );
}
</script>
```

**Comment by William-H-M** [comment]
Hi, as say in the docs .date() return [a moment object](http://eonasdan.github.io/bootstrap-datetimepicker/Functions/#date)

So as for what the [moment documents](http://momentjs.com/docs/) say:

1) [Months:](http://eonasdan.github.io/bootstrap-datetimepicker/Functions/#date) 

> Note: Months are zero indexed, so January is month 0.

That's why you're getting 4 instead of 5

2) [Day:](http://momentjs.com/docs/#/get-set/day/) 

> Note: Moment#date is for the date of the month, and Moment#day is for the day of the week.

So `myDate.get('day');` will return from 0 to 6 that is the day of the week, instead use [Date of month](http://momentjs.com/docs/#/get-set/date/) 

What that being said here I did [fiddle ](https://jsfiddle.net/William_/3gjkbj23/2/)that show difference between both cases.

As a side note it won't be easier to just get the string from the date with something like:

`$(this).children()[0].value` 

this done through `dp.change`

**Comment by c4327611** [comment]
thx a lot.
