### ISSUE TITLE
Problem with first setting of date on changed format

### ISSUE THREAD

**Issue by piotar** [Eonasdan/bootstrap-datetimepicker#2113]
If default data in datapicker is set on null and format was changed the picker won't work correctly.
version: 4.17.47

https://jsfiddle.net/0Ltv25o8/5126/

To reproduce problem:
You must choose some date and in console we can see moment object with full date time but our format is show only date. When you second click on input the event was fired and work correctly

**Comment by eluchsinger** [comment]
I believe, this is actually causing major problems with my application.

**Comment by danreg** [comment]
This issue still exists and is very bad!

**Comment by danreg** [comment]
This issue comes with 4.17.42. With 4.17.37 there is no problem.
Have also made a jsfiddle. https://jsfiddle.net/td74yqav/

Select a date in date picker and look at the iso date above. the time component is set to the current time, which is wrong.
Then click again on the datepicker widget.
You'll see that the change event is fired, and the time is set correctly to 00:00:00.

Please fix that. As there are over 100 commits in 4.17.42 I have no clue where this bug comes from
