### ISSUE TITLE
Unable to change the datetime format

### ISSUE THREAD

**Issue by AshishTechIT** [Eonasdan/bootstrap-datetimepicker#2123]
Hello,

I'm trying to change the format of my DateTime value as "dd-mm-yyyy hh:mm A", example: 18th June 2017, 11:30 AM should be displayed as 18-06-2017 11:30 AM in the textbox area.
I'm fetching the values of datetime field from database and I'm unable to change the value in the DateTime Picker in the required format.
**The only format that works is YYYY-MM-DD HH:mm A. 
The required format "dd-mm-yyyy hh:mm A" produces datetime in some unreadable format like Di-06-yyyy 07:13 PM.**

Below is what I'm currently having:-

```
$('.datetimepicker').datetimepicker({
            defaultDate: '@Model.StartTime',
            minDate: new Date(),
            format: 'YYYY-MM-DD HH:mm A',
            showTodayButton: true,
            sideBySide : true,     
            showClose: true,
            showClear: true,
            toolbarPlacement: 'top'

        });
```
With my ASP.net MVC code:-

```
           <td>
           @Html.DisplayFor(modelItem => item.StartTime)               
            </td>
            <td>
                @Html.ActionLink("Edit", "Employee", new { startTime = item.StartTime}) 
            </td>
```
And in my C# code, 

```
        [Display(Name = "Scheduled Time")]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy hh:mm}")]


        public DateTime StartTime
        { get;set;}
```

I've attached the screenshot of the Page for reference.

![sample](https://user-images.githubusercontent.com/18232622/27011459-83e2ece6-4ed9-11e7-933f-13228f9cc9a6.png)

Is there any way I can change the date in the required format with this DateTimePicker?

**Comment by William-H-M** [comment]
Hi, I see that on your table example your format string come as 09-04-2014 03:35, so it's a dd-MM-yyyy hh:mm, then on the format it should be `format: 'DD-MM-YYYY hh:mm A'` as you have it like HH:mm what for [moments documents](http://momentjs.com/docs/#/displaying/format/) it's interpreted like 24H format time.

> The required format "dd-mm-yyyy hh:mm A" produces datetime in some unreadable format like Di-06-yyyy 07:13 PM.

That's the same for moments as:
 dd: Su Mo ... Fr Sa
 yyyy: doesn't exist and that's why it's showing like a string

if any more help is need it just ask :)

**Comment by AshishTechIT** [comment]
Thanks William for response.
I've been trying to work on this issue, but its behaving differently.
Here's is my updated Javascript:-

```
<script type="text/javascript">
    $(function () {
        $('.datetimepicker').datetimepicker({

            defaultDate: '@Model.StartTime',
            minDate: new Date(),
            
            format: 'DD-MM-YYYY hh:mm A',
            showTodayButton: true,
            sideBySide : true,
           
            showClose: true,
            showClear: true,
            toolbarPlacement: 'top'

        });
    });
</script>
```

But it doesn't work in IE 11 and Firefox 45.9.0 on Windows 7. 
On load, the datetimepicker box appears blank and the default date appears when I click on the datetimepicker textbox. 
Also, Under Edit mode, the datetimepicker doesn't take the original time value as displayed in the table, instead it picks Current Time.

I've attached screenshot for reference.

![sample1](https://user-images.githubusercontent.com/18232622/27116902-4ec8a658-50f1-11e7-88d6-a7f773d9628d.png)


![sample2](https://user-images.githubusercontent.com/18232622/27116903-4ec917f0-50f1-11e7-9904-e1b282040223.png)

NOTE: Interestingly the same script works in Windows 10 with Microsoft Edge as shown in below screenshot.
![sample3](https://user-images.githubusercontent.com/18232622/27117183-0d456a2a-50f3-11e7-8155-7360d00ea07d.png)

Can you please suggest how to make it work?
And how to make the display common for all the browsers with Win7/10 support ?

**Comment by William-H-M** [comment]
Hi I see you're using MVC so let's do this

1) On your edit form I suppose you load things like this:

` @Html.EditorFor(model => model.Field, new { htmlAttributes = new { @class = "form-control" } })       ` 

As this is suppose to load the model with the data, so then this way data should be displayed from start right? So on the plugin there should be no need to set up defaultDate

On the plugin I see you set the minDate to: new Date(), what means that min date should be today at the current time, that's why that it should not take that 8:35 am, but you can kinda skip that using on the options

`useCurrent: false` 
that for 

> Also, Under Edit mode, the datetimepicker doesn't take the original time value as displayed in the table, instead it picks Current Time.

I've been using that way with MVC5 and have no problem till today, unfurtanly can show you any example right now as I'm on work right now :/

**Comment by AshishTechIT** [comment]
Thanks @William-H-M for your inputs and support.
I've made some changes in my code to make it work.

```
$(function () {

 $('#scheduleDate').datetimepicker({        

    useCurrent: false,
    minDate: new Date(),
    format: 'DD-MM-YYYY hh:mm A',
    showTodayButton: true,
    sideBySide: true,
    showClose: true,
    showClear: true,
    toolbarPlacement: 'top'

  });
});
```

In my Edit Form (Partial View):
```
 <div class='input-group date' id="scheduleDate">

 @Html.TextBoxFor(model => model.StartTime, new {  @class = "form-control" })
       <span class="input-group-addon">
            <span class="glyphicon glyphicon-calendar"></span>
       </span>

</div>
```
And I've changed the type of my model field "StartTime" from DateTime to String and made changes wherever necessary to Convert String to DateTime (using DateTime.ParseExact()) method with required format "dd-MM-yyyy hh:mm tt" .
This works now.
