### ISSUE TITLE
Is it possible to highlight a custom list of dates using datetimepicker functions

### ISSUE THREAD

**Issue by kishalaya1** [Eonasdan/bootstrap-datetimepicker#2147]
https://github.com/Eonasdan/bootstrap-datetimepicker/issues/1006

The issue was first mentioned here.Is this feature implemented in the latest version.Please reply. Because i can't find any documentaion for the same anywhere .Please help.
@Eonasdan : Please help. Please note that i am not asking for multiple slection. But highlighting mulltiple dates.
There are scenarios where we have two date pickers for date range selection. and if we have slected a start date and end date. we would like to highlight the range i=of in between dates in a slightly different color.Is it possible.Please help.

**Comment by Eonasdan** [comment]
I'm not making changes to this repo. If someone wants to put a PR for it fine. Otherwise the answer is the same "it includes a data-day- on the td of in the datepicker. Unfortunately, you'll have to do this any time the month view changes." This feature request might make it in to the new repo with events and callbacks.

**Comment by kishalaya1** [comment]
@Eonasdan : Thanx for the clarification
