### ISSUE TITLE
Need to understand the behaviour of min date 

### ISSUE THREAD

**Issue by Sidharthan1988** [Eonasdan/bootstrap-datetimepicker#2166]
```
   var e = new Date();
    e.setDate(e.getDate() - 8);
    $('#datetimepicker1').datetimepicker(
        {
            format: 'MM-DD-YYYY',
            minDate: e,
            maxDate: new Date(),
            useCurrent: false         
        }
);
```

even after i set the min date  to 8 i was showing 1 more day as enabled but i was not able  to select it .

**Comment by William-H-M** [comment]
Hi, for the problem of not able to selected it use
`moment(e).startOf('day')`

Why? because that date 'e' you gave there come with hours and minDate will take the hours too, so to set it up at 00:00 use that method up there.

Now about it's giving one more day I don't understand if today is 23 and 8 are taken out, should give 15 right? It's the same logic for this case here. 

PD: I know that you'll have mean is 8 days counting today, but for this case is not

**Comment by Sidharthan1988** [comment]
Will try and let you know

**Comment by William-H-M** [comment]
Hi, I'll be closing this as there's no feedback from original poster, feel free to re open it if need it.

**Comment by Sidharthan1988** [comment]
Thanks William ,this fixed my issue
