### ISSUE TITLE
Reset date When i change option on selection?

### ISSUE THREAD

**Issue by pala1993** [Eonasdan/bootstrap-datetimepicker#2175]
This repo is no longer actively monitor or supported. All future work is being done to https://github.com/tempusdominus/bootstrap-3

**Comment by William-H-M** [comment]
Hi, can you please be more specific with what you want to do, like add a description, thanks.

Note: please don't just a title a leave the specification blank, at least add if you've tried something or looked on stackoverflow.

**Comment by pala1993** [comment]
Hi William, first time selection option and date from datepicker it's working good but again i change the option and date from datepicker that old value is visible i want reset that one.

**Comment by William-H-M** [comment]
Hi, Oh I think I now understand, the problem is that you select a first date, then you want to select another but the first date still appears, is that so?

Can you try this fiddle and see if this happen? and try to use it on your project and see if any console error appears https://jsfiddle.net/William_/20oywuno/ other thing is please show me the code on how you're calling the plugin, thanks.

**Comment by pala1993** [comment]
Thanks William it's resolved..
