### ISSUE TITLE
How do i return a different value different from date displayed?

### ISSUE THREAD

**Issue by jayalvincorp** [Eonasdan/bootstrap-datetimepicker#2222]
Currently my format is like Monday, January 25
but i want the returned value to be different, 01/25/2018

**Comment by marko-hologram** [comment]
@jayalvincorp 
You could maybe use moment.js to transform dates where needed since it is a dependency for this library so you might as well use it. It would be something like:
```
var a = moment('Monday, January 25, 2018').format('MM/DD/YYYY');
console.log(a) // outputs 01/25/2018
```

The problem I'm seeing here is that you just have a date and not a full year (at least in your question) so moment cannot parse it since it will throw an error that it's an invalid date you are trying to pass to moment.js.

As a sidenote, question like that should maybe be better asked on Stackoverflow.com or googled since this is a place to report issues with the plugin, not really ask for advice on how to do things.

**Comment by William-H-M** [comment]
Closed as How-to Question
