### ISSUE TITLE
Keep same value on input when clicking same date or opening datepicker again

### ISSUE THREAD

**Issue by Lanaya1** [Eonasdan/bootstrap-datetimepicker#2224]
Hello !

I have a dp.change event who simply modify the value of the input to something more formatted.
The problem is when I click the same date twice, the value of the input return to base state.
Same when I have already chosen a date and opening the datepicker again.

https://jsfiddle.net/v4kmLfLx/2/

<img src="https://i.imgur.com/UI6WzFP.jpg" width="70%">
<img src="https://i.imgur.com/zskU2gv.jpg" width="70%">

Is that normal?

**Comment by William-H-M** [comment]
Uhhhh the reason is because there's no change, if you click the same place you had never changed places, you know what I mean? So... yeah is normal.

And BTW you're making this harder than need it.

Just use 
`  format: 'DD MMMM YYYY à HH:mm'`
No extra event need it, It'll be easier and less time-read code consuming, and no weird behavior happening and remember to update your base code current one is 4.17.47 you're using (on the fiddle at least) 4.15.35
