### ISSUE TITLE
JS error in Opencart's checkout - 'dateFormat' in bootstrap-datetimepicker.min.js

### ISSUE THREAD

**Issue by Rishika211** [Eonasdan/bootstrap-datetimepicker#2260]
Hello, I am having this error in checkout page of my site. Input field is defined as

`<div class="input-group datetime">`
          `<input type="text" name="custom_field[<?php echo $custom_field['location']; ?>][<?php echo $custom_field['custom_field_id']; ?>]" value="<?php echo $custom_field['value']; ?>" placeholder="<?php echo $custom_field['name']; ?>" data-date-format="YYYY-MM-DD HH:mm" id="input-payment-custom-field<?php echo $custom_field['custom_field_id']; ?>" class="form-control" />`
          `<span class="input-group-btn">`
          `<button type="button" class="btn btn-default"><i class="fa fa-calendar"></i></button>`
          `</span>`
`</div>`

And the jquery is written as

<script type="text/javascript">
$('.date').datetimepicker({
	pickTime: false
});
$('.time').datetimepicker({
	pickDate: false
});
$('.datetime').datetimepicker({
	pickDate: true,
	pickTime: true
});
</script> 

But still it shows error
"Uncaught TypeError: Cannot read property 'dateFormat' of undefined"

If you need any extra information, please let me know. Your quick response is highly appreciated. As the site is currently live and unable to process order.

**Comment by William-H-M** [comment]
Hi, not sure if you're using either:

1) A, _really_, older version of this picker
2) Using wrong picker

Why? Because the options `pickTime` `pickDate` are not used here.
`data-date-format="YYYY-MM-DD HH:mm"` is working for me as expected

You must check which datetimepicker you're using for this, moreover than that, this doesn't seems a bug but reither a missuing, if anymore problems enconter feel free to get back or find help on [StackOverflow](https://stackoverflow.com/questions/tagged/eonasdan-datetimepicker)
