### ISSUE TITLE
documentation error

### ISSUE THREAD

**Issue by Littleyux** [Eonasdan/bootstrap-datetimepicker#2288]
if you want to show "only date" the option is: format: 'L'

**Comment by iamstickfigure** [comment]
Also in the code for the "Date Only" section, it uses `id='datetimepicker3'` which is already in use by the "Time Only" section. So clicking the button for "Date Only" doesn't do anything.

**Comment by ghostal** [comment]
Yeah, that's correct.

@Eonasdan - The problem is with the example [here](http://eonasdan.github.io/bootstrap-datetimepicker/#date-only).

I can't open a PR for the docs page because I think eonasdan.github.io is a private repo, but the second instance of `datetimepicker3` (and the corresponding jQuery selector) needs to change to something like `datetimepicker3b`, as the element ID is already in use for the [previous example](http://eonasdan.github.io/bootstrap-datetimepicker/#time-only).
