### ISSUE TITLE
Conflict with bootstrap select

### ISSUE THREAD

**Issue by celogithub** [Eonasdan/bootstrap-datetimepicker#2291]
I am using the datetimepicker bootstrap but this is generating a conflict with the bootstrap select. When selecting a date in an input field the other selects simply disappear. What is going on?

**Comment by William-H-M** [comment]
Hi, this is way too broad right now, you will need to clarify some points first:

1) Which bootstrap select? [the one of silvio](https://developer.snapappointments.com/bootstrap-select/), because I've used it in other projects with the picker and no problems whatsover
2) What are you trying to achive?
3) What codes are you using, It'll be easier to help if we know what you're doing

If more help is need you can always ask to peers in [StackOverflow](https://stackoverflow.com/questions/tagged/eonasdan-datetimepicker)

**Comment by celogithub** [comment]
Hi, William.

I was using the jquery datetimepicker plugin that works great but in the mobile environment neither. For example when selecting the field it triggers the android keyboard and this is not a good experience for the client, so I decided to change the plugin.

I use the datetimeicker bootstrap in a form inside a modal box. When I select the field to change a date, it simply clears all other select fields.

This happened in one of the modal boxes, but I did the test in another form that is also presented inside a modal box and in that case this problem did not happen.

I have no idea what might be happening.

Thank you for your help.

**Comment by William-H-M** [comment]
Hi, mmm would need to see code because that's wieird, it happens in one but not the other

>selecting the field it triggers the android keyboard
use the [`ignoreReadonly`](http://eonasdan.github.io/bootstrap-datetimepicker/Options/#ignorereadonly) that way you will avoid that
