### ISSUE TITLE
minutes stepping issue

### ISSUE THREAD

**Issue by veera1908** [Eonasdan/bootstrap-datetimepicker#2296]
i made the stepping  minutes like below

//time picker          
            $('.slotTimePicker').datetimepicker({
                format      : 'HH:mm',
                stepping    : 1
            });

but it shows 5 minutes stepping like this

![time_slot](https://user-images.githubusercontent.com/47779880/63013763-9da40280-beaa-11e9-86ba-f4cb32ee8a39.png)

how can i fix this? i need minute stepping in 1 minutes

**Comment by William-H-M** [comment]
Hi, the reason is because on the code
https://github.com/Eonasdan/bootstrap-datetimepicker/blob/70eacba603023a511a611ed9cec277b379f655a5/src/js/bootstrap-datetimepicker.js#L787

As you can see the ternary operation is asking if the stepping is one the default to five

and you would have to change this line here, to remove the conditional
https://github.com/Eonasdan/bootstrap-datetimepicker/blob/70eacba603023a511a611ed9cec277b379f655a5/src/js/bootstrap-datetimepicker.js#L873-L879

**Comment by William-H-M** [comment]
Hi, I'll be closing this as there's no feedback from original poster, feel free to re open it if need it.

**Comment by DJManas** [comment]
> Hi, the reason is because on the code https://github.com/Eonasdan/bootstrap-datetimepicker/blob/70eacba603023a511a611ed9cec277b379f655a5/src/js/bootstrap-datetimepicker.js#L787
> 
> As you can see the ternary operation is asking if the stepping is one the default to five
> 
> and you would have to change this line here, to remove the conditional https://github.com/Eonasdan/bootstrap-datetimepicker/blob/70eacba603023a511a611ed9cec277b379f655a5/src/js/bootstrap-datetimepicker.js#L873-L879

Thanks. After I spent like hour of time checking why it is not working (stepping: 1) I managed to check issues here. After you have pointed out the code I came with quick workaround using stepping: 1.1 since there is check for stepping !== 1 and there is also Math.round() library and it works for me.

Thanks for your work on this library!
