### ISSUE TITLE
maxDate allows to switch calendar out of range

### ISSUE THREAD

**Issue by Anatolii-B** [Eonasdan/bootstrap-datetimepicker#2299]
Hello :) I faced with the issue when we define max Date, picker allows us to switch calendar out of range 
JSFiddle https://jsfiddle.net/y3tewubx/
![image](https://user-images.githubusercontent.com/13980088/64330070-fdd52280-cfd8-11e9-9189-a209d44a1847.png)

Could someone help? thanks :)

**Comment by jo2** [comment]
I'll take a look at it.

**Comment by jo2** [comment]
The problem is that `endDecade` is calculated from `startDecade + 100 years`. `startDecade` for the decade 2000 - 2100 is `1999-01-01T00:00:00` which works fine using the `isAfter` method of moment.js. `endDecade` would then be `2099-01-01T00:00:00` which obviously is not the end of the decade and not after your `maxDate`. Using the first date in the next decade though would work, so you just have to change the calculation of the `endDecade`. 

Pull Request in work.
