### ISSUE TITLE
dark-theme

### ISSUE THREAD

**Issue by dev-assassin** [Eonasdan/bootstrap-datetimepicker#2313]
Seeing your repo and doc, there is no to choose dark-theme. only exist default theme.
where can I add dark-theme?

**Comment by Maelstorm1973** [comment]
I have a solution, it's not ideal, but it does work.  From what I have gathered from the code, it uses a HTML template to outlay the different structures that makes up the display...mainly a condensed bootstrap table.  The colors are in a pre-programmed CSS file.  The way that I got around this was to add a click event to any and all fields that use this plugin.  The event handler then gets all elements that contain the class "datepicker".  Since it returns a collection, you have to use a for loop to iterate through the object, setting the foreground and background colors for each one on the div.

`function clickevent(e) {
	var datePickerObject = document.getElementsByClassName("datepicker");
	for (var i = 0; i < datePickerObject.length; i++) {
		datePickerObject[i].style.backgroundColor = "#000000";
		datePickerObject[i].style.color = "#FFFFFF";
	}
}`

The only issue with this that I have encountered is that the first time that the datepicker pops up, it will be white for a split second then it will go to the dark theme.  If you want to change the highlight color, that may involve changing the CSS itself since it's dynamically generated, or adding an option to set the colors to datepicker itself.  Since this forum is no longer actively being monitored, and there is no new information about what the new repository is, I have no idea when that will happen.
