### ISSUE TITLE
Allow readonly input

### ISSUE THREAD

**Issue by tsjoberg** [Eonasdan/bootstrap-datetimepicker#764]
Hi,

Believe in v4, this merge has gotten lost:

https://github.com/Eonasdan/bootstrap-datetimepicker/pull/681

Can you remerge this so readonly inputs allow for datepicker selection?

**Comment by Eonasdan** [comment]
shouldn't have been "lost" the `master` branch is what `v4beta` was.

Can you post a jsfiddle or screens of what's going on for you?

**Comment by tsjoberg** [comment]
Sure - this is the JSFiddle:

http://jsfiddle.net/tgsjoberg/Lzo7upc1/

You can see the first one works fine but the second one does not open calendar on click.

Per the initial merge believe the issue lies with this line:

https://github.com/Eonasdan/bootstrap-datetimepicker/blob/master/src/js/bootstrap-datetimepicker.js#L922

```javascript
if (input.prop('disabled') || input.prop('readonly') || widget) {
    return picker;
}
```

Should read:

```javascript
if (input.prop('disabled') || widget) {
    return picker;
}
```

**Comment by tsjoberg** [comment]
FYI @mtpultz as you came across feature initially

**Comment by tsjoberg** [comment]
@Eonasdan not sure if you see the merge linked vs the existing master branch now?

**Comment by tsjoberg** [comment]
Opened PR if you want to merge https://github.com/Eonasdan/bootstrap-datetimepicker/pull/793

**Comment by yanickrochon** [comment]
I can confirm that this has been lost. All my datetimepicker fields are `readonly` because we don't want users to enter values manually, and they ALL no longer work. I removed the attribute and they are now working as before. Having a `readonly` field is **not** the same as `disabled`; it should not prevent from changing their value programmatically. At least, allow something to override this behaviour.

**Comment by yanickrochon** [comment]
Alright, I managed to get an *acceptable* solution by doing 

```js
$('#txtProd-planned-date', formProd).closest('.input-group').datetimepicker({
  format: 'LL',
  minDate: new Date(),
  locale: moment.locale()
}).on('dp.change', function (e) {
  $('#hidProd-planned-date').val(e.date.toISOString());
}).end().on('keypress paste', function (e) {
  e.preventDefault();
  return false;
});
```
(**Note:** where a text field display a value in human readable format and the hidden field is the actual value being submitted with the form.)

This solution makes the field unmodifiable with basic methods of user input interactions and is acceptable to me for the time being.

**Comment by mattyas** [comment]
We also use the readonly to prevent user from entering manual input and force them to use the datetimepicker, when we don't want them to be able to enter we use disable. It would be great if the possibility would come back to do these distinctions again one way or another.

**Comment by Eonasdan** [comment]
the dev branch has a new feature` ignoreReadonly: true` will allow you to set an input to be `readonly` or `disabled` but still let the icon work.

**Comment by tsjoberg** [comment]
Thanks @Eonasdan ! I have tested this with the dev branch and all looks well. Closing this issue. Will re-open if theres anything I find not working.

Thanks again!

**Comment by mattyas** [comment]
Would it not be better with keeping the difference between disabled and readonly?

if (input.prop('disabled') || (!options.ignoreReadonly  && input.prop('readonly')) || widget) {

**Comment by yanickrochon** [comment]
Yes, there *is* a difference between `disabled` and `readonly`; a `disabled` field should not allow user interaction *at all* as it does not get submitted with the form, while the readonly may allow some interaction (i.e. programatically) since it's value does get submitted. The `ignoreReadonly` option should not ignore the disabled state of the field.

**Comment by tsjoberg** [comment]
@yanickrochon I actually did test this with jsfiddle and the disabled is working as expected (if input is disabled and readonly or disabled only it will not show picker)

Created a "test" fiddle with the cases:

http://jsfiddle.net/0Ltv25o8/342/

In your opinion are you OK with closing this issue @yanickrochon ?

**Comment by yanickrochon** [comment]
@tsjoberg haha! I was merely agreeing with @mattyas , and the code (I did not test it) seemed to perform as he was suggesting. I don't see any reason to argue any further, now :)

**Comment by mattyas** [comment]
@tsjoberg @yanickrochon the problem is only shown when an external icon is used.

$('#datetimepicker1').datetimepicker({
    ignoreReadonly : false
});
$('#datetimepicker1').datetimepicker({
    ignoreReadonly : true
});
 gives different results when input is disabled

 <div class="form-group">
                <div class='input-group date' id='datetimepicker1' >
                    <input type='text' class="form-control" disabled />
                    <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>

**Comment by mattyas** [comment]
```
        <div class="form-group">
                <div class='input-group date' id='datetimepicker1' >
                    <input type='text' class="form-control" disabled />
                    <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>
```

**Comment by yanickrochon** [comment]
@mattyas note that I do agree with your statement on the fact that the line

```js
if ((!options.ignoreReadonly  && (input.prop('disabled') || input.prop('readonly'))) || widget) {
```

implies that the `ignoreReadonly`, when `true`, will show the component if either the element is `disabled` or `readonly` (i.e. `if (false && (disabled || readonly))` evals to `false` in all cases, even when `disabled`, so the component is shown). The condition should, indeed, be

```js
if (input.prop('disabled') || (!options.ignoreReadonly && input.prop('readonly'))) || widget) {
```

**Comment by tsjoberg** [comment]
@yanickrochon @mattyas Yes I agree with both your points! ```disabled``` should be disabled regardless of ```readonly``` attribute or ```ignoreReadonly``` option :+1: 

@yanickrochon thanks for clarifying - my mind was spinning at bit there :-)

@Eonasdan you agree with @yanickrochon changes? (thanks @mattyas for catching it)

**Comment by yanickrochon** [comment]
@tsjoberg the updated [jsfiddle](http://jsfiddle.net/YanickRochon/0Ltv25o8/343/) with @mattyas 's point, shows that the condition is not right.

**Comment by tsjoberg** [comment]
Thanks @yanickrochon :+1:

**Comment by Eonasdan** [comment]
changed. disabled will still be disabled, the new option will only overwrite the `readonly`

**Comment by yanickrochon** [comment]
Any chance we can have this merged into master any time soon? Not that I want to push or anything :)

**Comment by Eonasdan** [comment]
the dev branch has a bug in it that'd I like to squash (hope to work on that tomorrow) before promoting dev to master

**Comment by damccull** [comment]
Once this is in master branch, how long until it's pushed to nuget?

**Comment by Eonasdan** [comment]
Assuming no other major issue with the dev branch come up this week, dev will be promoted to master March 7th.

**Comment by Ramisaa1** [comment]
In the current version the fix you mentioned up above isn't applied, correct it to the following please?

Line 990 with the following code:
if (input.prop('disabled') || (!options.ignoreReadonly && input.prop('readonly')) || widget) {

Needs to be changed to:
if (input.prop('disabled') && (!options.ignoreReadonly && input.prop('readonly')) || widget) {

Also there "seems" to be inconsistencies between the minified version and the non-minified

**Comment by yanickrochon** [comment]
@Ramisaa1 your proposed change is flawed. You suggest that it would prevent popping the calendar if the element is both disabled AND readonly? If either is not set (i.e. readonly and enabled, or disabled and not readonly), then the calendar would popop. This is not the desired effect.

The calendar should *not* popup if it is "disabled OR (readonly AND NOT ignoreReadonly)".

**Comment by Ramisaa1** [comment]
@yanickrochon don't know if you test out the code or not but i'll explain it out to you.
Line 990 with the following code:
if (input.prop('disabled') || (!options.ignoreReadonly && input.prop('readonly')) || widget) {

With that part above with the first || ,when working with the live code and not your theory i put in "disabled" into the input of the html code it works fine, if i put in "readonly" it works the same as the disabled did.

However if i change the first || into && to make it look like the following code:
if (input.prop('disabled') && (!options.ignoreReadonly && input.prop('readonly')) || widget) {

When done like this, the "disabled" still works as should while the "readonly" works the way it was intended as what the thread title is called "Allow readonly input".

Hench "disabled" should keep the calendar from popping up and keep people from typing into the field. While "readonly" should keep people from typing in a date into the field, as it allows a customer to only use the calendar popop so that said customers can't circumvent the options available on the calendar. Such as if lets say a business wants Saturdays and Sundays off the calendar, you want customers to select everything else but those days.

If you still don't get what I mean, look at tsjoberg jsfiddle link on the 3rd post of this thread, which happens to be using the current code of what I'm talking about, which clearly shows what he and i am talking about. Then on the 7th post, ironically you stated that what I'm currently talking about that the code in its current form is incorrect cause even you yourself on a previous version then the current version would not allow you to click on the input field for the calendar to popup. Also on the 9th post mattyas states pretty much what I'm talking about on the functionality of what the code should be doing.

So evidence points that what I'm asking and proposing is the correct answer, thanks.
