### ISSUE TITLE
Don't revert the date when input is invalid

### ISSUE THREAD

**Issue by am0d** [Eonasdan/bootstrap-datetimepicker#791]
See http://jsfiddle.net/cmpgtuwy/5/

I've come across an issue with the current behaviour regarding invalid input.  Currently, if the value entered is an invalid date, as soon as focus is lost the datepicker will revert the value to the previously valid date.

This is problem in the situation I am using it in (which can be replicated at the above link).

If the user was to type "Feb 29, 2015" into the input box (as an example of an invalid date), and then click the "Get Current Date" button, I would expect that I would get an invalid date object as the current value of the datepicker.  However, I simply get the previous valid value.

This is problematic when the button is actually a "Save and Close" button, because the user may not even see that the value reverted.  Since the `.date()` call returns a valid date, my validation routines don't fail and therefore the save would go ahead, but with a different value than the user is expecting.

Can we please have a way to force the invalid value to stay in there, and for the `.date()` call to return the invalid date?  That way I can call `.isValid()` on the `moment` object that gets returned, to see what the error is.

**Comment by tsjoberg** [comment]
Hi,

Maybe seperate from your issue but would it make sense to have the input readonly so that way user is forced to select date instead of typing? This is my current implementation to remove that user error factor. Unfortuantly the read only input is not working with the current version in master but is an easy fix pending this issue: https://github.com/Eonasdan/bootstrap-datetimepicker/issues/764

Thanks!

**Comment by am0d** [comment]
THat's a possibility, but power users like the ability to quickly type dates in, which can be much faster than picking them with the picker.

**Comment by vixriihi** [comment]
We would also like to be able to have invalid values in the field. In our case users can optionally use datetime picker to select date in specific format or input date in more freely manner (for example if they only know year). I thought the option userStrict would do it, but it seems to have no effect.

**Comment by Eonasdan** [comment]
[`extraFormats`](http://eonasdan.github.io/bootstrap-datetimepicker/Options/#extraformats) might solve your issues. PR #666 allows for you to include several valid format.

@vixriihi you should be able to include formats like `['YYYY']` if you want to allow them to enter just a year.

This option will auto format the input to the "master" format however. In other words, even if you allow typing in just the year, moment will convert that to `1/1/2015`.

Aside: `useStrict` is to make moment more strict when it considers a date valid or not.

**Comment by ArdentZeal** [comment]
+1 We would like to be able to keep userinput and just show him where the wrong field is.

**Comment by vixriihi** [comment]
@Eonasdan thanks for the useStrict clarification. Yes using that format would work, but in our case user should be able to input `2015` & `2015-02-03` & `hulapaloo` and all these are valid in our case. If the user chooses to use datetime picker the value would then be `2015-02-03`. I'd would like to see an option to allow "invalid" (from the datetime pickers viewpoint) values also.

**Comment by christianluckock** [comment]
We have a case where users can either pick a fixed date with the picker or enter an offset date such as *-1 Hour.   This is very common in many time series systems and the new picker just does not allow this once the picker is bound to the text area.   I was unable to upgrade to the latest momentjs and this control as a result.

Please allow the user to enter whatever they want.

**Comment by rwencel** [comment]
I could live with reverting it or clearing it out, but what I'm seeing right now with a time picker is that it's setting the time to 12:00 AM, which is a bit of a problem if the user doesn't notice that happen and saves anyway.  I looked at code but couldn't find any options that would prevent this behavior.

**Comment by Eonasdan** [comment]
`keepInvalid` has been added to the dev branch. setting this to true will not force the date to the previous date.

You can, in case you didn't realize, listen for `dp.error` and change the picker or throw your own error messages

**Comment by Eonasdan** [comment]
Assuming no other major issue with the dev branch come up this week, dev will be promoted to master March 7th.

**Comment by sowee15** [comment]
In our scenario, we let users manually input dates using the keyboard. If a user enters a valid date and then an invalid date, the `keepInvalid` flag at true makes it so that the invalid date stays in the textbox. However, the picker still returns the previous valid date when using the function `date()`. To avoid this, I added a handler to the `dp.error` event and in it I set `picker.date(null);`. However, this clears the invalid value entered in the textbox. In some cases, it would be preferable to keep the invalid value so it can just be adjusted.

So, what would be the recommended way of nullifying the picker value while retaining the invalid value in the textbox? One way I can think of is accessing the input text and setting its value, but before going this way I'd like to know your opinion.

Thanks!
