### ISSUE TITLE
auto close picker on picking date

### ISSUE THREAD

**Issue by gunjanvarshney** [Eonasdan/bootstrap-datetimepicker#861]
Hello eonasdan,

This is a great plugin and I think only in the market to give ability to pick time as well. great work!!!.

I was wondering if you can tell me how to auto close the pop-up once the date and time have been picked?

Thanks,
Gunjan

**Comment by webcmsdesigns** [comment]
The picker closes automatically when no time component is used via the option keepOpen which defaults to false. If a time component is used, considering how time is selected, I don't see a good way to determine when the users' selection is finished.

**Comment by Eonasdan** [comment]
you can also listen to the change event and call `close()`, but as @webcmsdesigns suggests, you can't be sure a user is done picking until the blur event. At which point the picker will close anyway

**Comment by bengalo** [comment]
I'm noticing this "issue" as well,
though it only happens when I'm using the picker on a jquery UI modal dialog.
clicking on the modal overlay will not close the picker.
I have some areas that will not be affected by the overlay through z-index. Clicking on those will trigger the blur and close the picker correctly
Dont know if thats related to some z-index thing or jquerys overlay intercepting clicks.. just in case anyone encounters this, maybe a start to find out whats happening
