### ISSUE TITLE
Duplicate Dates

### ISSUE THREAD

**Issue by mneimne** [Eonasdan/bootstrap-datetimepicker#881]
duplicate dates are generated on init.
![bug](https://cloud.githubusercontent.com/assets/1798784/6474136/fcb31acc-c206-11e4-9013-1865f2ae01d5.png)

**Comment by Eonasdan** [comment]
please provide a jsfiddle and indicate the version you are using

**Comment by mneimne** [comment]
no need check your demos page. using FireFox
![bug](https://cloud.githubusercontent.com/assets/1798784/6474243/dab519ce-c207-11e4-9b57-3055f49097b5.png)

**Comment by Eonasdan** [comment]
doesn't do it for me. I need more info. Timezone, browser, locale. Does it this in Chrome?

**Comment by mneimne** [comment]
Timezone : Beirut/Lebanon
Browser : FireFox 33.1 / Fedora 21
Locale : English
Chrome : 40 / Working fine

**Comment by Eonasdan** [comment]
interesting. There was another issue #855 having this issue in October. Do you have a duplicate date there?

Does it happen in any other month? What about in a different year?

**Comment by mneimne** [comment]
only march
march 2015 (2 28th)
march 2014 (2 29th)
march 2013 (2 30)
march 2013 (2 24th)

**Comment by Eonasdan** [comment]
you just have an extra day march where you're from then `:P`. I'll try to look in to it.

Can you try the dev branch?

**Comment by mneimne** [comment]
:smile:  ill try it within 10 - 12 hours , its late here

**Comment by Eonasdan** [comment]
Ok. Please let me know the results. Thanks

**Comment by alaasalman** [comment]
Not the reporter, but let me second the issue. It is due to DST kicking in on the 28th of March for 2015.  So .add(1, 'day') in 28-Mar-2015 00:00 GMT+2will turn it into 28-Mar-2015 23:00 GMT+2. Adding an hour more will turn it into GMT+3.

**Comment by mneimne** [comment]
it exists  on the development branch also :(

**Comment by Eonasdan** [comment]
some day.. maybe we'll get these blasted DST issues all worked out (-.- )

**Comment by alaasalman** [comment]
Would also like to add that this doesn't just cause an additional day to show up. It seems to be the cause of a TypeError in my case. Issue is thrown at line 608 but the culprint is that there's an "additional day" in that month so it throws off the rows construction. This is what my investigation has led to so far. I am attempting a workaround and will update this report when it works.

**Comment by alaasalman** [comment]
So I am thinking that the loop where that error is thrown(starting line 581) only deals with dates and so using a utc date there wouldn't have a negative effect, right? 

Specifically, making "currentDate" a utc date seems to takes care of this issue.

**Comment by alaasalman** [comment]
Tracked this down to browser implementation and handling of Date objects. Also confirmed by previous bug reports on moment.js. It has nothing to do with this library(thanks for the awesome work by the way). This seems to be Firefox specific(chromium has different behavior but works just fine).

For the benefit of anybody reaching here via google.  Adding an hour or two to the date on line 579 makes the DST time change work correctly. The problem was what to do when you add a number of milliseconds and the result is a time when a DST switch kicks in. Making it jump over that time(12am in my case) results in the correct calculation if you all you care about is the date rather than the actual time.

**Comment by Eonasdan** [comment]
Please check the development branch.

**Comment by erickmartim** [comment]
I'm on Brazil and I have this same issue, except it's on October month, like many issues here state. Thing is, I found a pull request on here, one dealing with timezones, that actually fixed the issue for me.
The pull request is the #1329 one. As far as I've tested, just the addition of this file from the moment library (https://cdnjs.cloudflare.com/ajax/libs/moment-timezone/0.4.0/moment-timezone-with-data-2010-2020.min.js) is the one responsible for fixing the problem. I take it off and it comes back. Using Firefox 41.0.1 on a Windows 8.
Hope that can help tracking down the issue somehow.

**Comment by anderstand** [comment]
Hello,

I've found the problem and "fixed" it. It's related to moment.js and timezone. Due to daylight saving time in Brazil, moment.js subtracts 1 hour on October. So, 29 October 00:00h becomes October 28 23:00h.

I never used momen.js, so probably it's not the best approach, but you can take a better look. My suggestion is to change line [715](https://github.com/Eonasdan/bootstrap-datetimepicker/blob/master/src/js/bootstrap-datetimepicker.js#L715) to something like:

`currentDate = viewDate.clone().startOf('M').startOf('week').add(1,'hours');`

You can check above the scripts I used and the results

```
currentdate = moment('2016-10-01 00:00:00').locale('en');
for(i=0; i< 32; i ++) {
  console.log(currentdate.add(1, 'days').format('LLLL'));
}
```
CONSOLE
Sunday, October 2, 2016 12:00 AM
Monday, October 3, 2016 12:00 AM
Tuesday, October 4, 2016 12:00 AM
Wednesday, October 5, 2016 12:00 AM
Thursday, October 6, 2016 12:00 AM
Friday, October 7, 2016 12:00 AM
Saturday, October 8, 2016 12:00 AM
Sunday, October 9, 2016 12:00 AM
Monday, October 10, 2016 12:00 AM
Tuesday, October 11, 2016 12:00 AM
Wednesday, October 12, 2016 12:00 AM
Thursday, October 13, 2016 12:00 AM
Friday, October 14, 2016 12:00 AM
**Saturday, October 15, 2016 12:00 AM
Saturday, October 15, 2016 11:00 PM**
Sunday, October 16, 2016 11:00 PM
Monday, October 17, 2016 11:00 PM
Tuesday, October 18, 2016 11:00 PM
Wednesday, October 19, 2016 11:00 PM
Thursday, October 20, 2016 11:00 PM
Friday, October 21, 2016 11:00 PM
Saturday, October 22, 2016 11:00 PM
Sunday, October 23, 2016 11:00 PM
Monday, October 24, 2016 11:00 PM
Tuesday, October 25, 2016 11:00 PM
Wednesday, October 26, 2016 11:00 PM
Thursday, October 27, 2016 11:00 PM
Friday, October 28, 2016 11:00 PM
Saturday, October 29, 2016 11:00 PM
Sunday, October 30, 2016 11:00 PM
Monday, October 31, 2016 11:00 PM
Tuesday, November 1, 2016 11:00 PM

```
currentdate = moment('2016-10-01 01:00:00').locale('en');
for(i=0; i< 32; i ++) {
  console.log(currentdate.add(1, 'days').format('LLLL'));
}
```
CONSOLE
Sunday, October 2, 2016 1:00 AM
Monday, October 3, 2016 1:00 AM
Tuesday, October 4, 2016 1:00 AM
Wednesday, October 5, 2016 1:00 AM
Thursday, October 6, 2016 1:00 AM
Friday, October 7, 2016 1:00 AM
Saturday, October 8, 2016 1:00 AM
Sunday, October 9, 2016 1:00 AM
Monday, October 10, 2016 1:00 AM
Tuesday, October 11, 2016 1:00 AM
Wednesday, October 12, 2016 1:00 AM
Thursday, October 13, 2016 1:00 AM
Friday, October 14, 2016 1:00 AM
**Saturday, October 15, 2016 1:00 AM**
Sunday, October 16, 2016 1:00 AM
Monday, October 17, 2016 1:00 AM
Tuesday, October 18, 2016 1:00 AM
Wednesday, October 19, 2016 1:00 AM
Thursday, October 20, 2016 1:00 AM
Friday, October 21, 2016 1:00 AM
Saturday, October 22, 2016 1:00 AM
Sunday, October 23, 2016 1:00 AM
Monday, October 24, 2016 1:00 AM
Tuesday, October 25, 2016 1:00 AM
Wednesday, October 26, 2016 1:00 AM
Thursday, October 27, 2016 1:00 AM
Friday, October 28, 2016 1:00 AM
Saturday, October 29, 2016 1:00 AM
Sunday, October 30, 2016 1:00 AM
Monday, October 31, 2016 1:00 AM
Tuesday, November 1, 2016 1:00 AM
Wednesday, November 2, 2016 1:00 AM
