### ISSUE TITLE
CSS fails to work

### ISSUE THREAD

**Issue by rjamesnw** [Eonasdan/bootstrap-datetimepicker#888]
After installing using Nuget to install v4 into an MVC web app, clicking the date controls correctly pops up the picker (without using any scripting), but it displayed without any CSS applied.  After inspection, I see that a DIV was rendered for the picker (at the end of the document, also as expected), but it fails to reference the 'bootstrap-datetimepicker-widget' class - instead, it only has the CSS class "datepicker" along with some other CSS class names.  If I add 'bootstrap-datetimepicker-widget' class to the HTML BODY tag, then it works, but it also messed up and tables in the body (as expected).  I instead renamed "bootstrap-datetimepicker-widget" to "datepicker" in the CSS and now it works.  There is no mention of this in the installation, so either it's not updated to the new version, or I'm missing something ... ?

**Comment by Eonasdan** [comment]
did you include the css file?

have to ask

**Comment by rjamesnw** [comment]
lol, yes. ;)

**Comment by akousmata** [comment]
I had a similar problem when installing into MVC 5 web app.  It would render, but it wouldn't display anything styled.  I had to fix several things from the nuget install:

1. Make sure to download and install System.Web.Optimization.Less if you need to support this through Bundling.
2.  Include the build.less file that comes with the nuget install in the bundle:  bundles.Add(new LessBundle("~/bundles/less").Include("~/Content/less/bootstrap-datetimepicker-build.less"));
3.  Add the new bundle to the _Layout or wherever you plan to us this:
@Styles.Render("~/bundles/less")
4.  From the base install, the bootstrap-datetimepicker-build.less file had the wrong file location for the variables.less file.  On line 2 it states @import "/Content/bootstrap/less/variables.less"; and had to change it to:  @import "/Content/bootstrap/variables.less";
5.  In the variables.less file, there are no @screen-sm-min, @screen-md-min, or @screen-lg-min variables, these have all been deprecated so in the _bootstrap-datetimepicker.less file I had to change any references for those by dropping the *-min part.

I am still experiencing problems with the icons not showing up because the fonts folder is at ~/Content/fonts rather than at the root of the project where the datetimepicker is expecting them.  Not sure how to get around that, but the previous steps got the css working and being applied for me without too much fussing around with adding/removing classes to the html.

**Comment by akousmata** [comment]
I figured out a workaround for the icons not working as well based on my last comment.  in bootstrap-datetimepicker-build.less, I had to include the following line:
`@import "/Content/bootstrap/glyphicons.less";`

**Comment by Eonasdan** [comment]
@akoskm doesn't the bootstrap.less file already reference that?

I guess I need to look at the bootstrap less source files and fix/clean up our file. (feel free to put in a PR `:)`)

I try to remember and change the path to the bootstrap less file in the NuGet package. Unfortunately, it has to be that way so grunt/travis can build the css

**Comment by akoskm** [comment]
@Eonasdan did you mean @akousmata ? :)

**Comment by Eonasdan** [comment]
@akoskm yes sorry :)

**Comment by akousmata** [comment]
@Eonasdan yes, it already references that, but we don't use bootstrap.less in our internal processes when building/running our sites.  I don't think you need to update your files, just mention that in your documentation that if you want to use the *.less package, that developers need to build the entire thing with bootstrap.less in order to get all the right dependencies.

**Comment by Eonasdan** [comment]
@rjamesnw can you send me a demo project?

**Comment by rjamesnw** [comment]
Sure, as soon as I get a chance (swamped with work).
