### ISSUE TITLE
Titles for icons

### ISSUE THREAD

**Issue by versak** [Eonasdan/bootstrap-datetimepicker#916]
For an upcoming release, could you add titles (tooltips) to the icons?

**Comment by btecu** [comment]
I would go even further and suggest have actual words instead of icons. Take the `Today` button, really the target is not that obvious and having `Today` text would be much more obvious.

You can easily fit two of those buttons on the same line, say `Clear` and `Today`...

Something like this:
![capture](https://cloud.githubusercontent.com/assets/7517745/6731463/78b2dd36-ce1b-11e4-893c-14d75461dfb1.PNG)

**Comment by Eonasdan** [comment]
@versak Please check the development branch. title's have been added to all icons and some links. Probably in v5 I'll change the `icon` to allow you to easily change the text

**Comment by Viniciussmb** [comment]
@Eonasdan Good morning, do you know when are u going to release version 5 of your date picker? I mean, when are you leaving alpha? Thank you!
