### ISSUE TITLE
Read and store dates as timestamps

### ISSUE THREAD

**Issue by jensljungblad** [Eonasdan/bootstrap-datetimepicker#941]
Is it possible to have the datepicker read and send timestamps, and only use the specified `format` for display purposes?

That is, can I use one format (unix timestamp) to read and submit dates, and another format (human readable) to display the date in the datepicker?

**Comment by Eonasdan** [comment]
you can use moment to get and set unix timestamps http://momentjs.com/docs/#/parsing/unix-offset/

**Comment by jensljungblad** [comment]
I know, but can I tell the datepicker to do that for me?

Let's say I want the datepicker to display dates on the `MM/DD/YYYY` format, but I want the submitted value to be a timestamp. Is that possible?

**Comment by Perzonallica** [comment]
This kind of functionality would be great!

**Comment by Eonasdan** [comment]
Won't this work for you: http://jsfiddle.net/Eonasdan/d59h8jpj/1/

**Comment by lcoulon** [comment]
Hello

I tried to get epoch timestamp working on my example, but it won't work : http://jsfiddle.net/lcoulon/r2xo8aoj/

Would you please tell what is wrong ?
I would like the form to send timestamp instead of formated date, how could i get this working ?

A jsfiddle example based on my example would be much appreciated.

**Comment by William-H-M** [comment]
@Icoulon, Hi you're in a totally different library your files reference to [this library](https://github.com/smalot/bootstrap-datetimepicker), there's where you should open an issue
