### ISSUE TITLE
Uncaught TypeError: defaultDate() date passed is invalid according to component setup validations

### ISSUE THREAD

**Issue by Arwym** [Eonasdan/bootstrap-datetimepicker#955]
Hello,

I've tried everything I could think of, but I keep getting the same error for dedaultDate().

"Uncaught TypeError: defaultDate() date passed is invalid according to component setup validations"

I first started by passing strings, and originally, I hadn't set up a date format; but depending on the passed date, either I had a deprecation warning, or this error, or both. I don't know what is wrong with my dates, if it is a bug, or a mistake on my end.

Fiddle: http://jsfiddle.net/0Ltv25o8/638/

Thank you in advance.

**Comment by Eonasdan** [comment]
in your fiddle you're trying to set the `defaultDate` to `03/27/2015` which is before the `minDate`, `3/30/2015`

two tips for you: if you're using the locale of `en` (default), moment provides a shortcut token to `MM/DD/YYYY h:mm:ss A` as `LT LTS`.

also:

```
var curDate = moment();
			// Capture current Appointment Date, IF any
			var apmDate = moment("03/27/2015 06:23:17 PM", "MM/DD/YYYY h:mm:ss A");
			// Ser a holder for the default date
			var defDate;
			if (apmDate.isValid()) {
				defDate = apmDate;
			} else {
				defDate = curDate;
// if I do this
defDate.add(1, 'd');
//it will also change curDate
			}
```

momemt objects are mutable and you need to use `moment(defDate)` or `defDate.clone()`. Otherwise, changes to make will apply to the original variable.

**Comment by Arwym** [comment]
Thank you very much! I hadn't noticed that. I have made sure now to compare both dates to avoid the error, and everything appears to be working now. I've updated the Fiddle, in the case somebody else has the same problem.

Once again, thank you. :)

**Comment by ChongDun** [comment]
likewise,awkward...
